<!-- <?=__FILE__ ?> -->
<div class="app">
        <header class="app-header">
            <h1 class="header-title">Overview</h1>
            <a class="logout-button" href="#">
                <img src="../img/logout-icon.png" alt="">
            </a>
        </header>
        <div class="content">
            <div class="user-container">
                <div class="profile-image">
                    <img src="../img/profile-pic.png" alt="">
                    <div class="active-icon"></div>
                    <a class="profile-msg-icon">
                        <img src="../img/msg-icon.png" alt="">
                    </a>
                    <h1 class="profile-name">Damian</h1>
                </div>
                <h2 class="profile-playing">Playing: Monkey Song</h2>
                <a class="teacher-icon">
                    <img src="../img/teacher-icon.png" alt="">
                    <span>Teacher</span>
                </a>
            </div>
            <div class="graph-container">
                <p class="graph-text">Studytime Average: 15min</p>
                <div style="width: 100%; height: 200px;" id="chart_div"></div>
            </div>
            <div class="stats-container">
                <div class="stats">
                    <p class="stats-title">Correctness</p>
                    <div class="bar-container bar-correct">
                        <div class="bar-stats" style="width: 20%">
                            <span>20%</span>
                        </div>
                    </div>
                </div>
                <div class="stats">
                    <p class="stats-title">Performance</p>
                    <div class="bar-container bar-perf">
                        <div class="bar-stats" style="width: 40%">
                            <span>40%</span>
                        </div>
                    </div>
                </div>
                <div class="stats">
                    <p class="stats-title">Rhythm</p>
                    <div class="bar-container bar-rhythm">
                        <div class="bar-stats" style="width: 60%">
                            <span>60%</span>
                        </div>
                    </div>
                </div>
                <div class="stats">
                    <p class="stats-title">Sight-reading</p>
                    <div class="bar-container bar-sight">
                        <div class="bar-stats" style="width: 100%">
                            <span>100%</span>
                        </div>
                    </div>
                </div>
                <div class="stats">
                    <p class="stats-title">Ear training</p>
                    <div class="bar-container bar-ear">
                        <div class="bar-stats" style="width: 20%">
                            <span>20%</span>
                        </div>
                    </div>
                </div>
                <div class="stats">
                    <p class="stats-title">Theory</p>
                    <div class="bar-container bar-theory">
                        <div class="bar-stats" style="width: 45%">
                            <span>45%</span>
                        </div>
                    </div>
                </div>
            </div>
            <div class="piano-container">
                <div class="tabs-container">
                    <div class="tab">
                        <div class="tab-box">
                            <span>Piano</span>
                        </div>
                        <div class="tab-box">
                            <span>Rhythm</span>
                        </div>
                        <div class="tab-box">
                            <span>Aural</span>
                        </div>
                        <div class="tab-box">
                            <span class="active">Theory</span>
                        </div>
                    </div>
                </div>
            </div>
                <div class="tabs-container">
                    <div class="tab">
                        <div class="tab-box">
                            <img class="tab-image" src="../img/01.png" alt="">
                        </div>
                        <div class="tab-box">
                            <img class="tab-image" src="../img/02.png" alt="">
                        </div>
                        <div class="tab-box">
                            <img class="tab-image" src="../img/03.png" alt="">
                        </div>
                        <div class="tab-box">
                            <img class="tab-image" src="../img/01.png" alt="">
                        </div>
                    </div>
                </div>
            </div>
        <footer class="app-footer">
            <a href="#">
                <img class="footer-icon" src="../img/home-icon.png" alt="">
            </a>
            <a href="#">
                <img class="footer-icon" src="../img/user-icon.png" alt="">
            </a>
            <a class="footer-notifications" href="#">
                <img class="footer-icon" src="../img/notif-icon.png" alt="">
                <span class="notif-number">2</span>
            </a>
            <a href="#">
                <img class="footer-icon" src="../img/web-icon.png" alt="">
            </a>
            <a href="#">
                <img class="footer-icon" src="../img/msg-icon-footer.png" alt="">
            </a>
        </footer>
    </div>
    <script src="https://canvasjs.com/assets/script/canvasjs.min.js"></script>
