<?php
    header('Access-Control-Allow-Origin: *');
    header('Access-Control-Allow-Methods: *');
    header( 'Access-Control-Allow-Headers: Authorization, Content-Type' );
?>

<!DOCTYPE html>
<html>
<!-- <?=__FILE__ ?> -->
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>Phalcon PHP Framework</title>
    <link rel="shortcut icon" type="image/x-icon" href="<?php echo $this->url->get('img/favicon.ico')?>" />
    <?php $this->assets->outputCss(); ?>
</head>

<body>
    <div class="container">
        <?php echo $this->getContent(); ?>
    </div>
    <!-- jQuery first, then Popper.js, and then Bootstrap's JavaScript -->
    <script
        src="https://code.jquery.com/jquery-3.4.1.min.js"
        integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="
          crossorigin="anonymous">
    </script>
    <script src="js/init.js"></script>
</body>
<?php $this->assets->outputJs(); ?>

</html>
